CSDN_PER_PAGE = 10
CSDN_COMMENT_PER_PAGE = 5
CSDN_COLLECTOR_PER_PAGE = 5
CSDN_USER_PER_PAGE = 5
CSDN_NOTIFICATION_PER_PAGE = 5
CSDN_ADMIN_POST_PER_PAGE = 10
CSDN_MANAGE_USER_PER_PAGE = 8
CSDN_MANAGE_COMMENT_PER_PAGE = 20
CSDN_MANAGE_CATEGORY_PER_PAGE = 10
CSDN_SEARCH_PER_PAGE = 5

WHOOSHEE_MIN_STRING_LEN = 1
